spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lecture-management-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,httpexchanges
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    level: "%5p [req:%X{requestId}]"

security:
  jwt:
    secret: ZGV2ZWxvcGVyLXNlY3JldC1rZXktZm9yLWxvdC1zaWduaW5nLXN0dWZm
    expiration: 3600000
