spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.hqcvezmtckpjlgpsnfwi}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: 'SET statement_timeout TO 0; SET search_path TO lecture_api, public'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: lecture_api
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
    default-schema: lecture_api
    liquibase-schema: public

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,threaddump,httpexchanges
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    level: "%5p [req:%X{requestId}]"

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:4173}
    allowed-methods: ${APP_CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
  sample-data:
    bootstrap-on-startup: true

security:
  jwt:
    secret: ${JWT_SECRET:change-me}
    expiration: ${JWT_EXPIRATION:3600000}
